name: Deploy to Azure Container Apps

on:
  push:
    branches: [main]

permissions:
  id-token: write       # required for OIDC
  contents: read 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}
          acrName: testdevscusacr
          containerAppName: test-dev-scus-aca
          resourceGroup: test-dev-scus-rg
          ingress: external  # optional
          targetPort: 80     # optional
