name: Print Secrets Array

on: 
  push:

jobs:
  print-array:
    runs-on: ubuntu-latest
    steps:
      - name: Print the raw secret
        run: echo "1st method/${{ secrets.ENV_SECRETS }}"

      - name: Save secret to file
        run: echo '2nd method/${{ secrets.ENV_SECRETS }}' > secret.json
