name: Deploy to Azure Container Apps (ACA)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write   # required for OIDC
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Azure using OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-oidc: true

      - name: Azure CLI - Deploy to ACA
        run: |
          # Variables
          RESOURCE_GROUP="test-dev-scus-rg"
          ACA_NAME="test-dev-scus-aca"
          ACR_NAME="testDevScusAcr"
          IMAGE="${ACR_NAME}.azurecr.io/hello-world-app:${GITHUB_SHA}"

          echo "Building image: $IMAGE"

          # Build & push image to ACR
          az acr build \
            --registry $ACR_NAME \
            --image $IMAGE \
            .

          # Create Container App if not exists
          #az containerapp create \
          #  --name $ACA_NAME \
          #  --resource-group $RESOURCE_GROUP \
          #  --environment test-dev-scus-cae \
          #  --image $IMAGE \
          #  --target-port 80 \
          #  --ingress external \
          #  --query properties.configuration.ingress.fqdn

          # Or update if already exists
          az containerapp update \
            --name $ACA_NAME \
            --resource-group $RESOURCE_GROUP \
            --image $IMAGE