name: Print Secrets Array

on: 
  push:

jobs:
  print-array:
    runs-on: ubuntu-latest
    steps:
      - name: Print the raw secret
        run: echo "1st Array/${{ secrets.ENV_SECRETS }}"

      - name: Print the raw secret
        run: echo "2nd Array with Value/${{ secrets.ENV_SECRETS_ARRAY }}"