name: Build and Deploy to ACA

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write     # for OIDC
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure login with OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Build and Push Docker image to ACR
        run: |
          RESOURCE_GROUP="test-dev-scus-rg"
          ACA_NAME="test-dev-scus-aca"
          ACR_NAME="testdevscusacr"
          IMAGE="${ACR_NAME}.azurecr.io/hello-world-app:${GITHUB_SHA}"

          echo "Building image: $IMAGE"

          # Log in to ACR
          az acr login --name $ACR_NAME

          # Build & push the Docker image (using Linux Dockerfile)
          docker build -t $IMAGE -f Dockerfile.linux .
          docker push $IMAGE

          # Deploy to ACA (update image)
          az containerapp update \
            --name $ACA_NAME \
            --resource-group $RESOURCE_GROUP \
            --image $IMAGE