name: Build and Deploy to ACA

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write     # for OIDC
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure login with OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Build and Push Docker image to ACR
        run: |
          RESOURCE_GROUP="test-dev-scus-rg"
          ACA_NAME="test-dev-scus-aca"
          ACR_NAME="testdevscusacr"
          IMAGE_SHA="${ACR_NAME}.azurecr.io/hello-world-app:${GITHUB_SHA}"
          IMAGE_LATEST="${ACR_NAME}.azurecr.io/hello-world-app:latest"

          echo "Building and pushing images: $IMAGE_SHA and $IMAGE_LATEST"

          az acr login --name $ACR_NAME

          #docker build -t $IMAGE_SHA -t $IMAGE_LATEST -f Dockerfile.linux .
          #docker push $IMAGE_SHA
          docker build -t $IMAGE_LATEST -f Dockerfile.linux .
          docker push $IMAGE_LATEST

      - name: Deploy in ACA
        run: | 
          # Deploy using stable tag
          az containerapp update \
            --name $ACA_NAME \
            --resource-group $RESOURCE_GROUP \
            --image $IMAGE_LATEST --debug
