name: Print the first value of an array secret

on: workflow_run

jobs:
  print-array:
    runs-on: ubuntu-latest
    steps:
      - name: Print the first value of the array
        run: echo $(fromJSON(secrets.ENV_SECRETS)[0])

      - name: Print the array
        run: echo $(fromJSON(secrets.ENV_SECRETS))

      - name: Print the first value of the array classic
        run: echo "${secrets.ENV_SECRETS}"